services:
  salus-api:
    build: .
    container_name: salus-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - redis
    command: sh -c "[ -f temp_env ] && mv temp_env .env || echo '.env jรก existe'; npm run all"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
